### ISSUE TITLE
I can see the pods running but not seeing the metrics in the GCP Metrics explorer

### ISSUE THREAD

**Issue by rubansutn** [halradaideh/gke-pvc-calculator#1]
Running the latest code and doesn't seem to be sending the metrics to GCP.
I don't see it in my GCP Metrics explorer anyway.
Any ideas?

**Comment by hradaideh** [comment]
idk really, did not use it since I wrote it.

**Comment by rubansutn** [comment]
ok a bit pointless then since you have an article publicising it => https://hradaideh.medium.com/pv-usage-as-metrics-on-gke-c4aa5365ebeb
Should really document it doesn't work, would be good to get it working.

**Comment by hradaideh** [comment]
no man, it was working, and used to use it for a while
then dropped it

at the time I wrote the article IT was working ...

**Comment by rubansutn** [comment]
any chance you can have a look at why the metrics stopped? maybe it's my issue but would be great to have it working if you can.

**Comment by hradaideh** [comment]
sorry I don't have time for it since I don't use it anymore

**Comment by rubansutn** [comment]
OK have updated a comment on the medium article to prevent others wasting time with this.
